### ISSUE TITLE
Why is "reimagining" not a word?

### ISSUE THREAD

**Issue by gajus** [streetsidesoftware/cspell-dicts#1425]
It is being flagged using this configuration:

```yaml
version: '0.3'
language: en
ignoreRegExpList:
  - /.*[0-9].*/
minWordLength: 5
words:
  - customeri
```

**Comment by nschonni** [comment]
0.3 isn't a valid value for version. It looks like it's only in the en-gb dictionary if you run `cspell trace reimagining`. It's likely because may be more commonly hyphenated as `re-imagining`

**Comment by Jason3S** [comment]
@gajus,

As Nick said, `cspell trace reimagining` will show you which dictionaries have the word. Looks like it is only in the en-gb dictionary.

Please be careful with `ignoreRegExpList` is applies to all the lines in a document. `/.*[0-9].*/` will ignore any LINE that has a number.

See image: Dark gray is ignored.
<img width="350" alt="image" src="https://user-images.githubusercontent.com/3740137/187845454-79eb03dc-7108-490f-a9f8-98cb285ea205.png">

You can use `cspell check <filename>` to see how `ignoreRegExp` impacts a file.

**Comment by gajus** [comment]
Closing as the original question has been addressed.

**Comment by Jason3S** [comment]
> without the ignoreRegExpList, cspell flags ppcpr1 as a misspelled word.

I suggest using [regex101](https://regex101.com/r/jNIEoX/1) to try it out first.

**Comment by gajus** [comment]
@Jason3S probably a separate problem, but regex does not seem to work all the time, e.g.

This is my configuration:

```yaml
allowCompoundWords: true
dictionaries:
  - en_us
  - en-gb
  - typescript
  - companies
  # contains various useful programming terms such as 'stringifiable'
  - cpp
ignoreRegExpList:
  # https://regex101.com/r/mqoody/1
  - "\b[a-zA-Z0-9]*[0-9]+[a-zA-Z0-9]*\b"
  - "'data-[a-z]*'"
language: en
minWordLength: 5
```

This is a test case:

https://regex101.com/r/mP6jYG/1

and it still highlights these words:

```
[..]/__tests__/ResourceDetails.test.tsx:22:27 - Unknown word (fezizlowdugqsvtss)
[..]/__tests__/ResourceDetails.test.tsx:27:27 - Unknown word (sholysbvuitn)
[..]/__tests__/ResourceDetails.test.tsx:46:20 - Unknown word (koyzugldpfbki)
[..]/__tests__/ResourceDetails.test.tsx:52:27 - Unknown word (bculqi)
```

**Comment by Jason3S** [comment]
There are two things going on:

1. `\b` needs to be `\\b`.
2. The regex has very bad performance.

This one is better: https://regex101.com/r/Xp1iuJ/1

Try this:
```yaml
allowCompoundWords: false # Not a good idea to make this `true` it will hide a LOT of errors.
dictionaries:
    - en_us
    - en-gb
    - typescript
    - companies
    # contains various useful programming terms such as 'stringifiable'
    - cpp
ignoreRegExpList:
    # https://regex101.com/r/mqoody/1
    - "/\\b[a-z]*([0-9]+[a-z]*)+\\b/gi"
    - "/'data-[a-z]+'/gi"
language: en
minWordLength: 5
```
