### ISSUE TITLE
sv language spell checker forbidden word

### ISSUE THREAD

**Issue by arkid15r** [streetsidesoftware/cspell-dicts#1770]
Hi everyone, 

I'd like to request you help to figure out whether the VS Code spell checker behavior is intended or not in one specific case. 

Actual behavior: the word `thailand` is marked as forbidden. Adding it to the list of folder/workspace/user settings doesn't help. It helps to add it to the ignored words list though.

![thailand](https://user-images.githubusercontent.com/2201626/210452054-cfe85946-d77f-4528-b781-ebb1b3c56671.png)

My question is: why https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/sv/src/hunspell/index.dic does contain `thailand/%AB` (intended/unintended)?

I noticed that `%` is used as a forbidden word marker [here](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/sv/src/hunspell/index.aff#L13). However, it's not clear to me whether it's a cause of the issue or just a coincidence as my knowledge of how cspell works is quite insufficient.

Thank you!

**Comment by Jason3S** [comment]
@arkid15r,

Thailand with a lowercase `t` is considered incorrect. Many dictionaries explicitly forbid country names with leading lowercase. We do not control the content of the dictionary. It gets imported from another public source.

The workaround is to ignore the word.

## Work arounds

These can be done in several ways:

### Comment in the code

```py
# cspell:ignore thailand
```

### `ignoreWord` in a config file

_`cspell.config.yaml`_
```yaml
# There are three different options here depending upon your needs.

# applies to all file types
ignoreWords:
  - thailand

# by filename
overrides:
  - filename: 
      - "**/*.py"
      - "**/*.{js,jsx}"
    ignoreWords:
      - thailand

# by programming languageId
languageSettings:
  - languageId: 
      - python
      - javascript
    ignoreWords:
      - thailand
``` 

### A Custom dictionary

_`cspell.config.yaml`_
```yaml
# Define a custom dictionary file
dictionaryDefinitions:
  - name: allowed_mispelled_words
    path: ./allowed_mispelled_words.txt
    noSuggest: true # all words in the dictionary are considered ignored.

# Below are three different ways to enable the dictionary

# applies to all file types
dictionaries:
  - allowed_mispelled_words

# by filename
overrides:
  - filename: 
      - "**/*.py"
      - "**/*.{js,jsx}"
    dictionaries:
      - allowed_mispelled_words

# by programming languageId
languageSettings:
  - languageId: 
      - python
      - javascript
    dictionaries:
      - allowed_mispelled_words
```
