### ISSUE TITLE
Fix Nginx software term

### ISSUE THREAD

**Issue by magnobiet** [streetsidesoftware/cspell-dicts#1784]
Dictionary: `software-terms`

Some software tool names usually can be whited in `lowercase` or `UPPERCASE`.

`nginx` is one of them, and has three different ways to write it.

Some references:

- NGINX - https://www.nginx.com/
- Nginx - https://en.wikipedia.org/wiki/Nginx
- nginx - https://hub.docker.com/_/nginx

![Terminal](https://user-images.githubusercontent.com/1743501/211102283-b2d5cccd-6242-47f5-8868-811d6063523d.png)

![Visual Studio Code](https://user-images.githubusercontent.com/1743501/211105070-ff45f713-f5e4-4b72-bc35-b7f2179de1a6.png)

It's necessary to add the term in the dictionary writing the three ways?

**Comment by Jason3S** [comment]
@magnobiet,

The issues is that Case/Accent Sensitivity is getting turned on. I'm guessing you are using the Portuguese dictionary.

The way Case/Accent Sensitivity is handled, it not idea. Enabling a language that is accent sensitive cause all checks to be accent sensitive.

It is on the road-map to fix this, but it hasn't happened yet.

The workaround is to use `languageSettings`:

## VS Code

`settings` -> `spell language settings`
<img width="724" alt="image" src="https://user-images.githubusercontent.com/3740137/211145826-cf1dfd50-742a-41cd-859a-584cf56d72d2.png">

**`settings.json`**
```json
"cSpell.languageSettings": [
    {
        "languageId": ["dockerfile"],
        "caseSensitive": false
    }
]

```

## CSpell config

**`cspell.config.yaml`**
```yaml
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
languageSettings:
  - languageId: # if the file type matches
    - javascript 
    - dockerfile
    - yaml
    # apply settings
    caseSensitive: false
```
