### ISSUE TITLE
Dictionary for Unity

### ISSUE THREAD

**Issue by bdovaz** [streetsidesoftware/cspell-dicts#3877]
Unity is a very famous videogame engine: https://unity.com/

Would you be willing to accept a PR to add this dictionary with words that I have found so far?

**Comment by Jason3S** [comment]
@bdovaz,

A PR is welcome, it can be done from the GitHub UI. Please add it to: [dictionaries/software-terms/src/coding-terms.txt](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/software-terms/src/coding-terms.txt)

**Comment by bdovaz** [comment]
@Jason3S I meant Unity API words that are many and are not in any official dictionary.

That why I suggested a particular dictionary for Unity

**Comment by Jason3S** [comment]
@bdovaz,

Thank you for the clarification.

If the API isn't too big, then I think we can add them to the [gaming-terms](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/gaming-terms) package.

Here are the steps:

1. Add a new file `unity-api.txt` to [gaming-terms/src](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/gaming-terms/src). 
1. Add a new target to [`cspell-tools.config.yaml`](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/gaming-terms/cspell-tools.config.yaml).
   ```yaml
    - name: 'unity-api'
      sources:
        - 'src/unity-api.txt'
      format: 'plaintext'
      targetDirectory: './dict'
      generateNonStrict: true
      compress: false
   ```
1. Add the new dictionary definition to [gaming-terms/cspell-ext.json](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/gaming-terms/cspell-ext.json)
1. Update [README.md](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/gaming-terms/README.md#manual-installation) manual installation.
