### ISSUE TITLE
Add 'opentype' which compliments 'truetype'

### ISSUE THREAD

**Issue by roydukkey** [streetsidesoftware/cspell-dicts#416]
'truetype' has already been added:

https://github.com/streetsidesoftware/cspell-dicts/blob/a73a7f649bdc1caa9f7bffe2c9c62927f9b81e34/dictionaries/fullstack/fullstack.txt#L159

Here is a popular usage of 'opentype' in the wild:

```scss
@font-face {
  font-family: 'Font Awesome 5 Free';
  font-style: normal;
  font-weight: 900;
  font-display: $fa-font-display;
  src: url('#{$fa-font-path}/fa-solid-900.eot');
  src: url('#{$fa-font-path}/fa-solid-900.eot?#iefix') format('embedded-opentype'),
  url('#{$fa-font-path}/fa-solid-900.woff2') format('woff2'),
  url('#{$fa-font-path}/fa-solid-900.woff') format('woff'),
  url('#{$fa-font-path}/fa-solid-900.ttf') format('truetype'),
  url('#{$fa-font-path}/fa-solid-900.svg#fontawesome') format('svg');
}
```

ref: [FortAwesome/Font-Awesome](https://github.com/FortAwesome/Font-Awesome/blob/d79d85c3fad85ad1885e87ed558f4afd6fce8289/scss/solid.scss#L7-L17)
